MadLibs/urls.py
from django.contrib import admin
from django.urls import include, path

# Custom views
from stories.views import home_view, create_story_view, play_story_view, user_posts_view, user_edit_post_view, user_delete_post_view
urlpatterns = [
    path('', home_view, name='home'), # Change the index page
    path('story/create/', create_story_view, name='mablibs_create'), # Change the index page
    path('story/play/<int:storyId>/', play_story_view, name='play'), # Change the index page
    path('story/play/<int:storyId>/display/', play_story_view, name='display'), # Change the index page
    
    path('story/users/<str:username>/posts/', user_posts_view, name='mablibs'), # Display a list of users posts
    path('story/users/<str:username>/posts/<int:storyId>/', user_edit_post_view, name='mablibs_edit'), # Edit one of the user posts
    path('story/users/<str:username>/posts/<int:storyId>/delete', user_delete_post_view, name='mablibs_delete'), # Edit one of the user posts


    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
]

users/urls.py
from django.urls import path

from users.views import register_view
from django.contrib.auth import views as authentication_views

from .forms import UserLoginForm

app_name = "users"
urlpatterns = [
    # Get login and logout view from django
    # Default looks up for templates in registration/ so we need to change it with template name
    # Login also requires an accounts/profile/ template. Which can be chaned in setting.py with LOGIN_URL
    path('login/', authentication_views.LoginView.as_view(template_name="users/login.html", extra_context={'site_title': "Login"}, authentication_form=UserLoginForm), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name="users/logout.html", extra_context={'site_title': "Logout"}), name='logout'),


    # Create a custom register view
    path('register/', register_view, name='register'),

]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm, UsernameField

# Can change the users here 
class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, label="First Name")
    last_name = forms.CharField(max_length=100, required=False, label="Last Name")
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"] # What variable do we want the from to display


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = UsernameField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Password',
        }
))

users/views.py
from django.shortcuts import redirect, render

from django.contrib.auth.decorators import login_required
from users.forms import RegistrationForm # My custom registration form

# Create your views here.
def register_view(request, *args, **kwargs):
    form = RegistrationForm(request.POST or None)
    if request.method == 'POST': # Check if the usersubmited the form correctly then redirect them
        if form.is_valid():
            form.save()
            # username = form.cleaned_data.get('username') # Get the username to display it back to the users
            # messages.success(request, f"Hello, {username}!\nYour account has been created.")
            return redirect('users:login') # Return them to portfolio database home page
    
    my_context = {
       "site_title": "Register",
        'form': form
    }
    return render(request, "users/register.html", my_context)

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="row d-flex justify-content-center align-items-center h-100">
  <div class="col-12 col-md-8 col-lg-6 col-xl-5">
    <div class="card" style="border-radius: 1rem;">
      <div class="card-body p-5 text-center">
        <div class="mb-md-5 mt-md-4 pb-5">
          <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
          <p class="mb-5">Please enter your login and password!</p>
          <form method="POST">
            {% csrf_token %}

            <div class="form-outline form-white mb-4">
              {{ form.username }}
              {{ form.username.errors }}
              <!-- <label class="form-label" for="{{ form.username.id_for_label }}">Username</label> -->
            </div>

            <div class="form-outline form-white mb-4">
              {{ form.password }}
              {{ form.password.errors }}
            </div>
            <button class="btn btn-outline-primary btn-lg px-5" type="submit">Login</button>
          </form>
          {% if form.errors %}
          <p class="alert alert-danger my-2 py-1" role="alert">Error: Username or Password is incorrect</p>
          {% endif %}
          <div>
            <p class="mb-0 mt-4">Don't have an account? <a href="{% url 'users:register' %}" class="fw-bold">Sign Up</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/logout.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<h1>You have been successfully logged out.</h1>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<h1>Register</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}