MadLibs/urls.py
from django.contrib import admin
from django.urls import include, path

# Custom views
from stories.views import home_view, create_story_view, play_story_view, user_posts_view, user_edit_post_view, user_delete_post_view
urlpatterns = [
    path('', home_view, name='home'), # Change the index page
    path('story/create/', create_story_view, name='mablibs_create'), # Change the index page
    path('story/play/<int:storyId>/', play_story_view, name='play'), # Change the index page
    path('story/play/<int:storyId>/display/', play_story_view, name='display'), # Change the index page
    
    path('story/users/<str:username>/posts/', user_posts_view, name='mablibs'), # Display a list of users posts
    path('story/users/<str:username>/posts/<int:storyId>/', user_edit_post_view, name='mablibs_edit'), # Edit one of the user posts
    path('story/users/<str:username>/posts/<int:storyId>/delete', user_delete_post_view, name='mablibs_delete'), # Edit one of the user posts


    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
]

users/urls.py
from django.urls import path

from users.views import register_view
from django.contrib.auth import views as authentication_views

from .forms import UserLoginForm

app_name = "users"
urlpatterns = [
    # Get login and logout view from django
    # Default looks up for templates in registration/ so we need to change it with template name
    # Login also requires an accounts/profile/ template. Which can be chaned in setting.py with LOGIN_URL
    path('login/', authentication_views.LoginView.as_view(template_name="users/login.html", extra_context={'site_title': "Login"}, authentication_form=UserLoginForm), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name="users/logout.html", extra_context={'site_title': "Logout"}), name='logout'),


    # Create a custom register view
    path('register/', register_view, name='register'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MabLib -
    {{ site_title }}
  </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  {% load static %}
  <link rel="stylesheet" href="{% static 'styles/style.css' %}">
  <!-- <link rel="icon" type="image/x-icon" href="{% static 'images/NewChicken.ico' %}"> -->
  {% block header %}
  {% endblock %}
</head>

<body class="bd-main">
  <header class="bd-header bd-navbar fixed-top">
    {% include 'navbar.html' %}
  </header>
  <main class="h-100 mt-5">
    <!-- Display messages -->
    <div class="container-fluid container-xxl pt-3 py-pd-4 bd-content h-100">
      {% block content %}
      {% endblock %}
    </div>
  </main>
  <footer>
  </footer>
</body>

</html>

templates/navbar.html
<nav class="container-xxl navbar navbar-expand-sm">
  <div class="container-fluid">
    <a class="navbar-brand py-1 bd-navbar-link" href="{% url 'home' %}">Mad Libs</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapsable" aria-controls="navbarCollapsable" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapsable">
      <ul class="navbar-nav navbar-left me-auto mb-2 mb-sm-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link bd-navbar-link" href="{% url 'mablibs_create' %}">Create</a>
        </li>
        <li class="nav-item">
          <a class="nav-link bd-navbar-link" href="{% url 'mablibs' request.user.username %}">My Madlibs</a>
        </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav navbar-right ms-auto mb-2 mb-sm-0">
        {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link btn bd-btn-secondary" href="{% url 'users:login' %}">Login / Register</a>
        </li>
        {% else %}
        <li class="nav-item">
          <div class="btn-group">
            <button type="button" class="dropdown-toggle btn bd-btn-secondary" data-bs-toggle="dropdown" data-bs-target="#dropdown-profile" aria-expanded="false">
              Hello,
              {{ user.username }}
            </button>
            <ul class="dropdown-menu" id="dropdown-profile">
              <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
            </ul>  
          </div>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>